Testing permissions in testing-hycom-download branch.

diff --git a/.github/workflows/sandbox.yml b/.github/workflows/sandbox.yml
--- a/.github/workflows/sandbox.yml
+++ b/.github/workflows/sandbox.yml
@@ -37,11 +37,15 @@ jobs:
               --rm \
               -v /home/somisana/ops/testing-hycom-download/20250506_00/downloaded_data/HYCOM:/tmp \
               ghcr.io/saeon/somisana-croco_cli_testing-hycom-download:latest \
-              download_hycom \
-                --domain 23,24,-37,-36 \
-                --depths 0,5 \
-                --run_date '2025-05-06 00:00:00' \
-                --hdays 5 \
-                --fdays 5 \
-                --savedir '/tmp/' \
-                --pad True && echo "Download completed" || echo "Download failed"
+              bash -c "\
+                mkdir -p /tmp/tmpdir && \
+                export TMPDIR=/tmp/tmpdir && \
+                echo 'Using TMPDIR=' \$TMPDIR && \
+                download_hycom \
+                  --domain 23,24,-37,-36 \
+                  --depths 0,5 \
+                  --run_date '2025-05-06 00:00:00' \
+                  --hdays 5 \
+                  --fdays 5 \
+                  --savedir '/tmp/' \
+                  --pad True && echo 'Download completed' || echo 'Download failed'"
